### ISSUE TITLE
headless-linux crashes with URLs containing IPs

### ISSUE THREAD

**Issue by sintax1** [preludeorg/operator-support#471]
v1.5.2 headless-linux agent crashes when running a ttp that contains a URL with an IP address. e.g. "http://1.2.3.4". Possibly part of the fact parsing logic?

Repro Steps:
1. Connect to a linux redirector.
2. Execute a ttp that contains a url with an IP Address.
3. Observe Operator lost connection with redirector and error output on redirector.

**Example ttp:**
```yaml
id: b09fc6e5-e925-4e63-8013-b7b2448e9f88
name: test
description: Auto-Generated
tactic: Auto-Generated
technique:
  id: T0000
  name: Auto-Generated
metadata:
  authors: []
  tags: []
  payloads: {}
platforms:
  linux:
    sh:
      command: echo "http://1.2.3.4/"
```

**headless-linux Error Output:**
```bash
[server] operator connected
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```
