### ISSUE TITLE
Extended payload.bytes support to core Operator

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#535]
Currently the payload.bytes special keyword is used for Sliver TTPs, but it would be very helpful to support this inside Operator as a core functionality.

The idea would be to allow TTPs like:
```yaml
platforms:
  windows:
    bof:
      command: '{"Name":"coff-loader", "ServerStore":false, "Args":"#{payload.bytes}", "Export":"LoadAndRun"}'
      payload: arp.x64.o
```

Even better would be combining this with:
- https://github.com/preludeorg/operator-support/issues/458

Then we could do stuff like:
```yaml
metadata:
  payloads:
    arp.x64.o: shasum
platforms:
  windows:
    bof:
      command: '{"Name":"coff-loader", "ServerStore":false, "Args":"#{payload.arp.x64.o.bytes}", "Export":"LoadAndRun"}'
```
