### ISSUE TITLE
v1.7.0 Hello World training question doesn't verify

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#557]
I have deployed the Hello World TTP as follows

![image](https://user-images.githubusercontent.com/22311332/180902949-21521d50-8fad-41c3-91b9-bef36a91e1ee.png)

But the training question won't verify.

![image](https://user-images.githubusercontent.com/22311332/180903031-ac307f7b-0b31-4536-9e34-b8e1309c4d13.png)

Here is my YAML:

```
id: c1dbb57f-c4be-4169-916d-f2dba44e922c
name: Hello World
description: print console message
tactic: Discovery
technique:
  id: T1016
  name: System Network Configuration Discover
metadata:
  authors: []
  tags: []
  payloads: {}
platforms:
  windows:
    cmd:
      command: echo hello world
```
